version: '3.1'

services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
  db:
    image: postgres:13.0-alpine
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./habr_proj/.env.db
  web:
    build: ./habr_proj
    restart: always
    container_name: web
    command: gunicorn habr_proj.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/habr_proj/web/static
      - media_volume:/home/habr_proj/web/media
    expose:
      - 8000
    env_file:
      - ./habr_proj/.env
    depends_on:
      - db
      - redis
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/habr_proj/web/static
      - media_volume:/home/habr_proj/web/media
    ports:
      - 80:80
    depends_on:
      - web
  celery:
    build: ./habr_proj
    restart: always
    command: celery -A habr_proj worker -l info
    volumes:
      - celery_volume:/usr/src/app/
    env_file:
      - ./habr_proj/.env
    depends_on:
      - redis
  dashboard:
    build: ./habr_proj
    command: flower -A habr-proj --port=5555 --broker=redis://redis:6379/0
    env_file:
      - ./habr_proj/.env
    depends_on:
      - web
      - redis
      - celery
volumes:
  postgres_data:
  static_volume:
  media_volume:
  celery_volume: