version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./habr_proj/.env.db
  web:
    build: ./habr_proj
    command: gunicorn habr_proj.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/habr_proj/web/static
      - media_volume:/home/habr_proj/web/media
    expose:
      - 8000
    env_file:
      - ./habr_proj/.env
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/habr_proj/web/static
      - media_volume:/home/habr_proj/web/media
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume: