# Generated by Django 3.2.8 on 2022-06-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Help',
        ),
    ]
