# Generated by Django 3.2.8 on 2022-06-16 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_auto_20220616_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyUserStatus',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('notify_body', models.TextField(blank=True, verbose_name='Содержание уведомления')),
                ('status_send', models.CharField(choices=[('CR', 'Создано'), ('PR', 'Процесс отправки'), ('CPT', 'Отправка успешна'), ('ERR', 'Ошибка отправки')], default='CR', max_length=3, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status_user', models.CharField(choices=[('REG', 'Пользователь зарегистрирован'), ('ACT', 'Учетная  запись активирована'), ('BLC', 'Учетная запись временно заблокирована'), ('DEL', 'Учетная запись удалена')], default='REG', max_length=3, verbose_name='Статус пользователя')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователю')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotifyPostStatus',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('notify_body', models.TextField(blank=True, verbose_name='Содержание уведомления')),
                ('status_send', models.CharField(choices=[('CR', 'Создано'), ('PR', 'Процесс отправки'), ('CPT', 'Отправка успешна'), ('ERR', 'Ошибка отправки')], default='CR', max_length=3, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status_post', models.CharField(choices=[('NEW', 'Поступил новый на модерацию'), ('TO', 'На модерации'), ('MOD', 'Прошел модерацию'), ('BLC', 'Заблокирован (не прошел модерацию)'), ('DEL', 'Удален')], default='TO', max_length=3, verbose_name='Статус хаба')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postnotify', to='posts.posts', verbose_name='Хаб')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователю')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotifyLike',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('notify_body', models.TextField(blank=True, verbose_name='Содержание уведомления')),
                ('status_send', models.CharField(choices=[('CR', 'Создано'), ('PR', 'Процесс отправки'), ('CPT', 'Отправка успешна'), ('ERR', 'Ошибка отправки')], default='CR', max_length=3, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likenotify', to='posts.postslikes', verbose_name='Лайк')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователю')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotifyComment',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('notify_body', models.TextField(blank=True, verbose_name='Содержание уведомления')),
                ('status_send', models.CharField(choices=[('CR', 'Создано'), ('PR', 'Процесс отправки'), ('CPT', 'Отправка успешна'), ('ERR', 'Ошибка отправки')], default='CR', max_length=3, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('to_moder', models.BooleanField(default=False, verbose_name='Для модератора')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentnotify', to='posts.comment', verbose_name='Комментарий')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователю')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
