# Generated by Django 3.2.8 on 2022-06-21 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifyapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotifyLike',
        ),
    ]
