# Generated by Django 3.2.8 on 2022-06-21 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220621_1715'),
        ('notifyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifycomment',
            options={'verbose_name': 'Уведомление по комментариям', 'verbose_name_plural': 'Уведомления по комментариям'},
        ),
        migrations.AlterModelOptions(
            name='notifylike',
            options={'verbose_name': 'Уведомление по лайкам', 'verbose_name_plural': 'Уведомления по лайкам'},
        ),
        migrations.AlterModelOptions(
            name='notifypoststatus',
            options={'verbose_name': 'Уведомление по хабу', 'verbose_name_plural': 'Уведомления по хабам'},
        ),
        migrations.AlterModelOptions(
            name='notifyuserstatus',
            options={'verbose_name': 'Уведомление по пользователю', 'verbose_name_plural': 'Уведомления по пользователю'},
        ),
        migrations.RenameField(
            model_name='notifyuserstatus',
            old_name='status_user',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='notifypoststatus',
            name='status_post',
        ),
        migrations.AddField(
            model_name='notifycomment',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AddField(
            model_name='notifycomment',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.likes', verbose_name='Лайк'),
        ),
        migrations.AddField(
            model_name='notifycomment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.posts', verbose_name='Хаб'),
        ),
        migrations.AddField(
            model_name='notifycomment',
            name='status',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='notifylike',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='notifylike',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AddField(
            model_name='notifylike',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.posts', verbose_name='Хаб'),
        ),
        migrations.AddField(
            model_name='notifylike',
            name='status',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='notifylike',
            name='to_moder',
            field=models.BooleanField(default=False, verbose_name='Для модератора'),
        ),
        migrations.AddField(
            model_name='notifypoststatus',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='notifypoststatus',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AddField(
            model_name='notifypoststatus',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.likes', verbose_name='Лайк'),
        ),
        migrations.AddField(
            model_name='notifypoststatus',
            name='status',
            field=models.CharField(choices=[('NEW', 'Поступил новый на модерацию'), ('TO', 'На модерации'), ('MOD', 'Прошел модерацию'), ('BLC', 'Заблокирован (не прошел модерацию)'), ('DEL', 'Удален')], default='NEW', max_length=3, verbose_name='Статус хаба'),
        ),
        migrations.AddField(
            model_name='notifypoststatus',
            name='to_moder',
            field=models.BooleanField(default=False, verbose_name='Для модератора'),
        ),
        migrations.AddField(
            model_name='notifyuserstatus',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='notifyuserstatus',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AddField(
            model_name='notifyuserstatus',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.likes', verbose_name='Лайк'),
        ),
        migrations.AddField(
            model_name='notifyuserstatus',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.posts', verbose_name='Хаб'),
        ),
        migrations.AddField(
            model_name='notifyuserstatus',
            name='to_moder',
            field=models.BooleanField(default=False, verbose_name='Для модератора'),
        ),
        migrations.AlterField(
            model_name='notifycomment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='notifycomment',
            name='status_send',
            field=models.CharField(choices=[('CR', 'Создано'), ('PR', 'Процесс отправки'), ('CPT', 'Отправка успешна'), ('ERR', 'Ошибка отправки')], default='CR', max_length=3, verbose_name='Статус отпраки'),
        ),
        migrations.AlterField(
            model_name='notifylike',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.likes', verbose_name='Лайк'),
        ),
        migrations.AlterField(
            model_name='notifylike',
            name='status_send',
            field=models.CharField(choices=[('CR', 'Создано'), ('PR', 'Процесс отправки'), ('CPT', 'Отправка успешна'), ('ERR', 'Ошибка отправки')], default='CR', max_length=3, verbose_name='Статус отпраки'),
        ),
        migrations.AlterField(
            model_name='notifypoststatus',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.posts', verbose_name='Хаб'),
        ),
        migrations.AlterField(
            model_name='notifypoststatus',
            name='status_send',
            field=models.CharField(choices=[('CR', 'Создано'), ('PR', 'Процесс отправки'), ('CPT', 'Отправка успешна'), ('ERR', 'Ошибка отправки')], default='CR', max_length=3, verbose_name='Статус отпраки'),
        ),
        migrations.AlterField(
            model_name='notifyuserstatus',
            name='status_send',
            field=models.CharField(choices=[('CR', 'Создано'), ('PR', 'Процесс отправки'), ('CPT', 'Отправка успешна'), ('ERR', 'Ошибка отправки')], default='CR', max_length=3, verbose_name='Статус отпраки'),
        ),
    ]
