# Generated by Django 3.2.8 on 2022-06-21 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_postslikes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifyapp', '0002_delete_notifylike'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyLike',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('notify_body', models.TextField(blank=True, verbose_name='Содержание уведомления')),
                ('status_send', models.CharField(choices=[('CR', 'Создано'), ('PR', 'Процесс отправки'), ('CPT', 'Отправка успешна'), ('ERR', 'Ошибка отправки')], default='CR', max_length=3, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likenotify', to='posts.postslikes', verbose_name='Лайк')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователю')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
