# Generated by Django 3.2.8 on 2022-06-22 15:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifyapp', '0002_auto_20220622_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyCategory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Наименование категории')),
            ],
        ),
        migrations.AddField(
            model_name='notifycomment',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifyapp.notifycategory', verbose_name='Категория уведомлений'),
        ),
        migrations.AddField(
            model_name='notifylike',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifyapp.notifycategory', verbose_name='Категория уведомлений'),
        ),
        migrations.AddField(
            model_name='notifypoststatus',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifyapp.notifycategory', verbose_name='Категория уведомлений'),
        ),
        migrations.AddField(
            model_name='notifyuserstatus',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifyapp.notifycategory', verbose_name='Категория уведомлений'),
        ),
    ]
