# Generated by Django 3.2.8 on 2022-06-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifyapp', '0002_auto_20220617_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifypoststatus',
            name='status',
            field=models.CharField(choices=[('NEW', 'Поступил новый на модерацию'), ('TO', 'На модерации'), ('MOD', 'Прошел модерацию'), ('BLC', 'Заблокирован (не прошел модерацию)'), ('DEL', 'Удален')], default='NEW', max_length=3, verbose_name='Статус хаба'),
        ),
    ]
