# Generated by Django 3.2.8 on 2022-06-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifyapp', '0003_auto_20220622_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifycomment',
            name='category',
            field=models.CharField(choices=[('PST', 'Уведомления к постам'), ('LK', 'Уведомления к лайкам'), ('CMT', 'Уведомления к коментариям'), ('USR', 'Уведомления по учетной записи')], max_length=3, null=True, verbose_name='Категория уведомлений'),
        ),
        migrations.AlterField(
            model_name='notifylike',
            name='category',
            field=models.CharField(choices=[('PST', 'Уведомления к постам'), ('LK', 'Уведомления к лайкам'), ('CMT', 'Уведомления к коментариям'), ('USR', 'Уведомления по учетной записи')], max_length=3, null=True, verbose_name='Категория уведомлений'),
        ),
        migrations.AlterField(
            model_name='notifypoststatus',
            name='category',
            field=models.CharField(choices=[('PST', 'Уведомления к постам'), ('LK', 'Уведомления к лайкам'), ('CMT', 'Уведомления к коментариям'), ('USR', 'Уведомления по учетной записи')], max_length=3, null=True, verbose_name='Категория уведомлений'),
        ),
        migrations.AlterField(
            model_name='notifyuserstatus',
            name='category',
            field=models.CharField(choices=[('PST', 'Уведомления к постам'), ('LK', 'Уведомления к лайкам'), ('CMT', 'Уведомления к коментариям'), ('USR', 'Уведомления по учетной записи')], max_length=3, null=True, verbose_name='Категория уведомлений'),
        ),
        migrations.DeleteModel(
            name='NotifyCategory',
        ),
    ]
