# Generated by Django 3.2.8 on 2022-06-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifyapp', '0004_auto_20220622_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifycomment',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='notifylike',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='notifypoststatus',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='notifyuserstatus',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя пользователя'),
        ),
    ]
