# Generated by Django 3.2.8 on 2022-06-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220616_1527'),
        ('notifyapp', '0004_auto_20220620_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifycomment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='notifycomment',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.likes', verbose_name='Лайк'),
        ),
        migrations.AlterField(
            model_name='notifycomment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.posts', verbose_name='Хаб'),
        ),
        migrations.AlterField(
            model_name='notifylike',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='notifylike',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.likes', verbose_name='Лайк'),
        ),
        migrations.AlterField(
            model_name='notifylike',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.posts', verbose_name='Хаб'),
        ),
        migrations.AlterField(
            model_name='notifypoststatus',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='notifypoststatus',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.likes', verbose_name='Лайк'),
        ),
        migrations.AlterField(
            model_name='notifypoststatus',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.posts', verbose_name='Хаб'),
        ),
        migrations.AlterField(
            model_name='notifyuserstatus',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='notifyuserstatus',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.likes', verbose_name='Лайк'),
        ),
        migrations.AlterField(
            model_name='notifyuserstatus',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.posts', verbose_name='Хаб'),
        ),
    ]
