# Generated by Django 3.2.8 on 2022-06-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_habruser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='habruser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='user_avatar', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='habruser',
            name='specialization',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Специализация'),
        ),
    ]
