# Generated by Django 3.2.8 on 2022-06-14 18:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Текст Хаба'),
        ),
    ]
