# Generated by Django 3.2.8 on 2022-06-14 18:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=ckeditor.fields.RichTextField(default=None, verbose_name='Комментарий'),
        ),
    ]
