# Generated by Django 3.2.8 on 2022-06-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220616_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='Проверен'),
        ),
        migrations.AddField(
            model_name='posts',
            name='status',
            field=models.CharField(choices=[('TO', 'На модерации'), ('PUB', 'Опубликован'), ('BLC', 'Заблокирован'), ('NPUB', ' Не опубликован')], default='TO', max_length=10, verbose_name='Статус хаба'),
        ),
    ]
