# Generated by Django 3.2.8 on 2022-06-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_posts_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='status',
        ),
        migrations.AddField(
            model_name='posts',
            name='status_moderation',
            field=models.CharField(choices=[('TO', 'На модерации'), ('PM', 'Одобрен'), ('BLC', 'Заблокирован')], default='TO', max_length=10, verbose_name='Статус модерации'),
        ),
    ]
