# Generated by Django 3.2.8 on 2022-06-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_postslikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='views',
            field=models.BigIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
