# Generated by Django 3.2.8 on 2022-07-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20220707_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postslikes',
            name='like_or_dislike',
        ),
        migrations.AddField(
            model_name='postslikes',
            name='is_like',
            field=models.BooleanField(default=True, verbose_name='Флаг лайк'),
        ),
    ]
