# Generated by Django 3.2.8 on 2022-07-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20220708_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='post_dislike',
        ),
    ]
